export const productDefault = {
  products: [
    {
      id: 1,
      title: '10 LBS.',
      image: 'icon1',
      price: '10 lbs. /$',
      isFavorite: false,
    },
    {
      id: 2,
      title: '10 LBS.',
      image: 'icon2',
      price: '8 lbs. /$',
      isFavorite: false,
    },
    {
      id: 3,
      title: '10 LBS.',
      image: 'icon3',
      price: '5 lbs. /$',
      isFavorite: false,
    },
    {
      id: 4,
      title: '10 LBS.',
      image: 'icon4',
      price: '10 lbs. /$',
      isFavorite: false,
    },
    {
      id: 5,
      title: '10 LBS.',
      image: 'icon2',
      price: '8 lbs. /$',
      isFavorite: false,
    },
    {
      id: 6,
      title: '10 LBS.',
      image: 'icon3',
      price: '5 lbs. /$',
      isFavorite: false,
    },
    {
      id: 7,
      title: '10 LBS.',
      image: 'icon4',
      price: '10 lbs. /$',
      isFavorite: false,
    },
    {
      id: 8,
      title: '10 LBS.',
      image: 'icon2',
      price: '8 lbs. /$',
      isFavorite: false,
    },
    {
      id: 9,
      title: '10 LBS.',
      image: 'icon3',
      price: '5 lbs. /$',
      isFavorite: false,
    },
    {
      id: 10,
      title: '10 LBS.',
      image: 'icon3',
      price: '5 lbs. /$',
      isFavorite: false,
    },
  ],
};
